version: '3.3'

services:

  transcript-backend:
    container_name: discord-backend
    build: .
    image: discord-backend:dev
    restart: always 
    env_file: 
      - ./.env
    ports: 
      - 8081:8081

  postgres:
    image: postgres:13
    container_name: discord_postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5445:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: