"""Create working related table

Revision ID: 20a8e22776b7
Revises: 1de19e25ee69
Create Date: 2023-02-10 16:50:42.969205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a8e22776b7'
down_revision = '1de19e25ee69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_sheet',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('apply_date', sa.VARCHAR(), nullable=False),
    sa.Column('leave_date', sa.VARCHAR(), nullable=False),
    sa.Column('hours', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'leave_date')
    )
    op.create_table('overtime_sheet',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('project', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('hours', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'project')
    )
    op.create_table('time_sheet',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('datetime', sa.VARCHAR(), nullable=False),
    sa.Column('project', sa.VARCHAR(), nullable=False),
    sa.Column('hours', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'project')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # op.alter_column('emoji_info', 'emoji_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_unique_constraint(None, 'emoji_info', ['emoji_eng'])
    # op.create_unique_constraint(None, 'event_points', ['user_id'])
    # op.alter_column('menu', 'number',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.create_unique_constraint(None, 'menu', ['number'])
    # op.create_unique_constraint(None, 'user_info', ['user_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user_info', type_='unique')
    # op.drop_constraint(None, 'menu', type_='unique')
    # op.alter_column('menu', 'number',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(None, 'event_points', type_='unique')
    # op.drop_constraint(None, 'emoji_info', type_='unique')
    # op.alter_column('emoji_info', 'emoji_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.drop_table('user_profile')
    op.drop_table('time_sheet')
    op.drop_table('overtime_sheet')
    op.drop_table('leave_sheet')
    # ### end Alembic commands ###
